### ISSUE TITLE
Drop Lodash dependency

### ISSUE THREAD

**Issue by OliverJAsh** [fvilers/disable-react-devtools#1]
Hi, thanks for packing this up! It would be good to drop the dependency on `lodash` because it's quite large. It shouldn't be too hard—maybe just use `typeof` instead? WDYT?

**Comment by fvilers** [comment]
Hi, yes, this is a good suggestion. I've been a bit lazy on this one.

**Comment by fvilers** [comment]
Version 1.1.0 without lodash has been published on NPM.
