### ISSUE TITLE
React dev tools throw console error

### ISSUE THREAD

**Issue by mlturner88** [fvilers/disable-react-devtools#6]
Whenever the production site loads after using this library/function, React dev tools runs into a `null` exception.

```
react_devtools_backend.js:13502 Uncaught TypeError: Cannot read property 'forEach' of null
    at initBackend (react_devtools_backend.js:13502)
    at setup (react_devtools_backend.js:10032)
    at welcome (react_devtools_backend.js:9979)
```

It seems the `renderers` property on the global `__REACT_DEVTOOLS_GLOBAL_HOOK__` object is being iterated over. I'll submit a PR to address this.

**Comment by fvilers** [comment]
Thanks ! I'll release the patched version asap.
